(() => {
'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const data={
 people:[['Morgan Reed','morgan','Engineering','Systems Architect','MR'],['Jordan Lee','jordan','Product','Product Lead','JL'],['Riley Chen','riley','Research','Research Engineer','RC'],['Avery Brooks','avery','Design','Product Designer','AB'],['Sam Rivera','sam','Operations','Operations Lead','SR'],['Taylor Kim','taylor','AI Systems','ML Engineer','TK']],
 posts:[
  {name:'Morgan Reed',initials:'MR',time:'18 min',body:'The new SenseOS shell is now running as plain browser-ready HTML. Mobile startup no longer depends on client-side decompression.',tags:['release','senseos'],likes:14,comments:4},
  {name:'Jordan Lee',initials:'JL',time:'1 hr',body:'Romeo now has a dedicated workspace route with collective, deep, and GPT-only modes mapped to the real service contract.',tags:['romeo','ai'],likes:21,comments:7},
  {name:'Riley Chen',initials:'RC',time:'3 hr',body:'Research workspace review is scheduled for Monday. Add any architecture questions to the project board before then.',tags:['research'],likes:9,comments:2}
 ],
 files:[['SenseOS Product Brief','DOC','Edited 8 min ago'],['Romeo Architecture','MD','Edited 26 min ago'],['Release Assets','FOLDER','12 items'],['Brand System','FOLDER','18 items'],['Backend Environment','ENV','Private'],['Roadmap 2026','SHEET','Edited yesterday']],
 projects:[['SenseOS','Unified company workspace',72,'sense-framework.github.io'],['Project Romeo','Multi-model intelligence service',64,'project_romeo'],['SENSE Framework','Mathematical organism architecture',48,'sense-framework'],['Zeroform','AI-native programming language',36,'zeroform']],
 chats:{system:[['System','Temporary administrator preview is active.'],['You','The interface check has started.']],morgan:[['Morgan Reed','Can you review the release board?'],['You','Yes. I am checking the mobile flow now.']],romeo:[['Romeo','The chat workspace is available from the floating R control.']]}
};
let currentChat='system',deferredInstall=null,toastTimer;
const titleMap={home:'SENSE',feed:'Company Feed',messages:'Messages',people:'People',files:'Files',projects:'Projects',ai:'SENSE AI',calendar:'Calendar',admin:'Administration',system:'System'};
function toast(text){const n=$('#toast');n.textContent=text;n.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>n.classList.remove('show'),2400)}
function show(view){$$('.view').forEach(v=>v.classList.toggle('active',v.id===`view-${view}`));$$('.nav-target').forEach(b=>b.classList.toggle('active',b.dataset.view===view));$('#viewTitle').textContent=titleMap[view]||'SENSE';location.hash=`/${view}`;$('.workspace').scrollTop=0}
function openApp(){sessionStorage.setItem('sense.preview','1');$('#lock').classList.add('hidden');$('#auth').classList.add('hidden');$('#app').classList.remove('hidden');const hash=location.hash.replace(/^#\//,'');show(titleMap[hash]?hash:'home')}
function renderFeed(){const markup=data.posts.map((p,i)=>`<article class="panel post"><header><div class="person-avatar">${p.initials}</div><span><b>${p.name}</b><small>${p.time}</small></span><button>•••</button></header><p>${p.body}</p><div class="tags">${p.tags.map(t=>`<span>#${t}</span>`).join('')}</div><footer><button data-like="${i}">♡ ${p.likes}</button><button>◌ ${p.comments}</button><button>↗ Share</button></footer></article>`).join('');$('#feedList').innerHTML=markup;$('#homeActivity').innerHTML=data.posts.slice(0,3).map(p=>`<div class="activity-row"><div class="person-avatar">${p.initials}</div><span><b>${p.name}</b><small>${p.body.slice(0,76)}…</small></span><time>${p.time}</time></div>`).join('');$$('[data-like]').forEach(b=>b.onclick=()=>{const p=data.posts[+b.dataset.like];p.likes++;b.textContent=`♥ ${p.likes}`})}
function renderPeople(filter=''){const q=filter.toLowerCase();$('#peopleGrid').innerHTML=data.people.filter(p=>p.join(' ').toLowerCase().includes(q)).map(p=>`<article class="person-card"><div class="person-avatar big">${p[4]}</div><h3>${p[0]}</h3><span>@${p[1]}</span><p>${p[3]} · ${p[2]}</p><div><button data-message="${p[1]}">Message</button><button>Profile</button></div></article>`).join('');$$('[data-message]').forEach(b=>b.onclick=()=>{currentChat=b.dataset.message==='morgan'?'morgan':'system';show('messages');renderChat()})}
function renderFiles(){$('#fileGrid').innerHTML=data.files.map(f=>`<article class="file-card"><div>${f[1]==='FOLDER'?'▣':'▤'}</div><h3>${f[0]}</h3><span>${f[1]}</span><small>${f[2]}</small></article>`).join('')}
function renderProjects(){$('#projectGrid').innerHTML=data.projects.map(p=>`<article class="panel project-card"><header><div class="project-icon">${p[0][0]}</div><button>•••</button></header><h2>${p[0]}</h2><p>${p[1]}</p><small>${p[3]}</small><div class="progress"><i style="width:${p[2]}%"></i></div><footer><span>${p[2]}%</span><b>Open project</b></footer></article>`).join('')}
function renderConversations(){const list=[['system','S','System','Preview environment ready'],['morgan','MR','Morgan Reed','Can you review the release?'],['romeo','R','Romeo','Multi-model workspace']];$('#conversationList').innerHTML=`<div class="panel-head"><div><small>INBOX</small><h2>Messages</h2></div></div>`+list.map(x=>`<button class="conversation ${x[0]===currentChat?'active':''}" data-chat="${x[0]}"><div class="person-avatar">${x[1]}</div><span><b>${x[2]}</b><small>${x[3]}</small></span></button>`).join('');$$('[data-chat]').forEach(b=>b.onclick=()=>{currentChat=b.dataset.chat;renderChat();$('.messages-layout').classList.add('chat-open')})}
function renderChat(){renderConversations();const names={system:'System',morgan:'Morgan Reed',romeo:'Romeo'};$('#chatTitle').textContent=names[currentChat];$('#chatStream').innerHTML=(data.chats[currentChat]||data.chats.system).map(m=>`<div class="chat-bubble ${m[0]==='You'?'me':''}"><small>${m[0]}</small>${m[1]}</div>`).join('');$('#chatStream').scrollTop=$('#chatStream').scrollHeight}
function renderAdmin(){$('#adminUsers').innerHTML=data.people.slice(0,5).map((p,i)=>`<div class="admin-user"><span><b>${p[0]}</b><small>@${p[1]} · ${i===0?'Administrator':'User'}</small></span><button>${i===0?'Active':'Manage'}</button></div>`).join('')}
function renderCalendar(){const start=3,days=31,cells=[];for(let i=0;i<start;i++)cells.push('<span></span>');for(let d=1;d<=days;d++)cells.push(`<button class="${d===24?'today':''}">${d}${[24,25,27].includes(d)?'<i></i>':''}</button>`);$('#days').innerHTML=cells.join('')}
function search(q){const items=[...Object.values(titleMap),...data.people.map(p=>p[0]),...data.projects.map(p=>p[0]),...data.files.map(f=>f[0])];const matches=items.filter(x=>x.toLowerCase().includes(q.toLowerCase())).slice(0,10);$('#searchResults').innerHTML=matches.length?matches.map(x=>`<button>${x}<span>Open</span></button>`).join(''):'<p>No results</p>'}
function bind(){setTimeout(()=>$('#boot').classList.add('done'),800);$('#power').onclick=()=>$('#auth').classList.remove('hidden');$('#preview').onclick=openApp;$('#signIn').onclick=()=>toast('Backend not connected. Use temporary administrator preview.');$$('.nav-target').forEach(b=>b.addEventListener('click',()=>show(b.dataset.view)));$('#postButton').onclick=()=>{const i=$('#postInput');if(!i.value.trim())return;data.posts.unshift({name:'Temporary Administrator',initials:'MA',time:'now',body:i.value.trim(),tags:['update'],likes:0,comments:0});i.value='';renderFeed();toast('Post saved locally')};$('#peopleFilter').oninput=e=>renderPeople(e.target.value);$('#chatForm').onsubmit=e=>{e.preventDefault();const i=$('#chatInput');if(!i.value.trim())return;(data.chats[currentChat]||=data.chats.system).push(['You',i.value.trim()]);i.value='';renderChat();toast('Message saved locally')};$('#chatBack').onclick=()=>$('.messages-layout').classList.remove('chat-open');$('#uploadButton').onclick=()=>toast('File upload activates when the backend is connected.');$('#newProject').onclick=()=>toast('New project flow opened in preview.');$('#broadcastButton').onclick=()=>toast('Broadcast transmitted in local preview.');$('#newEvent').onclick=()=>toast('Event composer opened in preview.');$('#saveApi').onclick=()=>{const v=$('#apiEndpoint').value.trim();if(v){localStorage.setItem('sense.api',v);toast('Workspace API saved')}else toast('Enter an API URL')};$('#apiEndpoint').value=localStorage.getItem('sense.api')||'';$('#logout').onclick=()=>{sessionStorage.removeItem('sense.preview');location.reload()};$('#searchButton').onclick=()=>{$('#searchOverlay').classList.remove('hidden');$('#globalSearch').focus()};$('#closeSearch').onclick=()=>$('#searchOverlay').classList.add('hidden');$('#globalSearch').oninput=e=>search(e.target.value);document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('#searchOverlay').classList.remove('hidden');$('#globalSearch').focus()}if(e.key==='Escape')$('#searchOverlay').classList.add('hidden')});$('#aiForm').onsubmit=e=>{e.preventDefault();const i=$('#aiInput');if(i.value.trim())toast('SENSE AI backend is not connected yet.');i.value=''};$('#openRomeoFromAI').onclick=()=>window.SENSE_ROMEO?.open();$('#installButton').onclick=async()=>{if(deferredInstall){deferredInstall.prompt();await deferredInstall.userChoice;deferredInstall=null}else toast('Use Safari Share → Add to Home Screen.')};window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e});window.addEventListener('hashchange',()=>{const v=location.hash.replace(/^#\//,'');if(titleMap[v]&&!$('#app').classList.contains('hidden'))show(v)});if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});if(sessionStorage.getItem('sense.preview')==='1')openApp()}
function init(){renderFeed();renderPeople();renderFiles();renderProjects();renderChat();renderAdmin();renderCalendar();bind()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
